### PR TITLE
Update BKAT export

### PR DESCRIPTION
**Pull request by der-eismann**
Data is from version 3.0.1 of the BKAT from https://www.govconnect.de/Downloads and includes the new stuff that's valid from 9.11.21.

### CODE REVIEW

**Comment by phoet** [comment]
Hi Philipp, i contacted them today and asked for an update. As of yesterday, there was no updated version.

**Comment by der-eismann** [comment]
The unzipped files of version 3.0.1 have timestamps from `10. Nov 08:02` and contain the new violations marked with `'2021-11-09-00.00.00.0000'` as the date, so I guess this is the updated version. But I wouldn't rule out a misunderstanding here :slightly_smiling_face: Let's see what they answer you then.

**Comment by phoet** [comment]
sorry, that was misleading. they updated the downloads after i contacted them this morning. so this new version can be used for an update of the weg.li site. it's not an identical version, so some slight adaptions are necessary.

**Comment by der-eismann** [comment]
Closing because of 8793aca275a519c7b77f560c22e22ab4f3a87101

**Comment by phoet** [comment]
@der-eismann i wanted to merge your changes, but unfortunately it had a lot of whitespace conflicts and i was too lazy to resolve them. thank's for the update anyways.

**Comment by der-eismann** [comment]
> it had a lot of whitespace conflicts

That's what I feared when I saw that you are using a script for the export :slightly_smiling_face: No problem!

**Pull request closed without merging**
