### PR TITLE
Introduce rack-utf8_sanitizer

### PR DESCRIPTION
**Pull request by mnin**
The Sanitizer should prevent that requests with a different encoding lead to an exception.

### CODE REVIEW

**Comment by phoet** [comment]
There are test-failures

**Comment by mnin** [comment]
@phoet thanks, I have seen it, will fix later.

**Comment by mnin** [comment]
@phoet do you think `QUERY_STRING` is enough to handle the requests?

**Comment by phoet** [comment]
I don't know, what exactly are you trying to fix?

**Comment by mnin** [comment]
These exceptions:

```ruby
ArgumentError: invalid byte sequence in UTF-8
activesupport (6.0.3.2) lib/active_support/core_ext/object/blank.rb:127:in `match?'
activesupport (6.0.3.2) lib/active_support/core_ext/object/blank.rb:127:in `blank?'
activesupport (6.0.3.2) lib/active_support/core_ext/object/blank.rb:26:in `present?'
actionpack (6.0.3.2) lib/action_controller/metal/strong_parameters.rb:459:in `require'
```

**Comment by phoet** [comment]
I don't know if that will get rid of them 🤷‍♂️ Could you find out?

**Comment by phoet** [comment]
closing in favor of https://github.com/weg-li/weg-li/pull/270

**Pull request closed without merging**
