### PR TITLE
update config to rails 7

### PR DESCRIPTION
**Pull request by phoet**

### CODE REVIEW

**Comment by der-eismann** [comment]
I think this PR just broke wegli :/ When I try to create a new report, enter all details and press continue, I get `Beweisfotos muss ausgefüllt werden` even though I uploaded them. Could you check this?

**Comment by phoet** [comment]
can't reproduce, please reload and try agin

**Comment by phoet** [comment]
ah, it's after editing the form, gotcha

**Comment by phoet** [comment]
it was clear enough, just such an odd place for this to fail.

**Comment by phoet** [comment]
fixed by 00b07ddccd9c9382ccaa42a6a9857682a2818a07

default was not set properly

**Comment by der-eismann** [comment]
Awesome, thanks for the quick fix!

**Comment by phoet** [comment]
sorry for the disruption, i should have tested the whole path

**Pull request merged**
