### PR TITLE
dockerized ruby app

### PR DESCRIPTION
**Pull request by MarlonSchultz**
# Description

I dockerized the initial setup of ruby and postgreSQL. Since i dont use ruby, nor postgreSQL on a daily basis, this might be useful for others as well. It runs weg-li locally without the need to install ruby and or postgreSQL. You will however need docker and docker-compose on your machine.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How to test?

Change into Directory "docker" and run

`docker-compose up`.

Please be aware that your port 3000 must not be occupied by another service, or another local instance of a ruby server.

**Test Configuration**:
5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

!!NOT TESTED ON MAC!!

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation 
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by phoet** [comment]
thx for you contribution.

i didn't work with docker for quite a while, but as i remember there was no need to configure networks manually. it was possible to access the service via name i.e. `postgres` and pass those as environment variables into the container for usage in `database.yml` and the like.

**Comment by MarlonSchultz** [comment]
Yes — you are correct. I chose the network approach to touch as little of your code as possible. That's the reason I ended up using sed. I couldn't map the postgres container to the ruby container as localhost. It is however possible to use a service name like you mentioned. That would remove the need of a dedicated network and docker would resolve the names.

**Comment by MarlonSchultz** [comment]
My main point/question however is this: If the project doesnt need this. Just throw it away and ill keep it in my fork, if I ever want to contribute to the projecgt Ruby wise. :)

**Comment by phoet** [comment]
having docker as an option for development setup is good 👍

**Comment by MarlonSchultz** [comment]
Great.

Let me change what you suggested (no network), and ill change the docker volume as well. Where would you typically put your ruby files on a server?

Learning on top: Ask beforehand if this is a good idea, before creating a PR.

**Comment by phoet** [comment]
there is no "typical" location. i guess i would go with this: https://docs.docker.com/compose/rails/

**Comment by phoet** [comment]
thx @MarlonSchultz

**Pull request merged**
